[package]
name = "rsgen-sol-wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
solana-sdk = "2.1.7"
futures = "0.3.31"
futures-util = "0.3.31"
